// Package singbox defines the sing-box configuration fragments used by twarp.
package singbox

// Config is the complete sing-box configuration generated by twarp.
type Config struct {
	Log          Log          `json:"log"`
	DNS          DNS          `json:"dns"`
	Inbounds     []Inbound    `json:"inbounds"`
	Outbounds    []Outbound   `json:"outbounds"`
	Route        Route        `json:"route"`
	Experimental Experimental `json:"experimental"`
}

// Log configures sing-box logging.
type Log struct {
	Level string `json:"level"`
}

// Inbound describes a sing-box TUN or mixed inbound.
type Inbound struct {
	Type       string   `json:"type"`
	Tag        string   `json:"tag"`
	Address    []string `json:"address,omitempty"`
	AutoRoute  bool     `json:"auto_route,omitempty"`
	Listen     string   `json:"listen,omitempty"`
	ListenPort uint16   `json:"listen_port,omitempty"`
}

// Outbound describes a sing-box outbound connection.
type Outbound struct {
	Type           string       `json:"type"`
	Tag            string       `json:"tag"`
	Server         string       `json:"server,omitempty"`
	ServerPort     uint16       `json:"server_port,omitempty"`
	Version        string       `json:"version,omitempty"`
	UUID           string       `json:"uuid,omitempty"`
	Flow           string       `json:"flow,omitempty"`
	TLS            *OutboundTLS `json:"tls,omitempty"`
	DomainResolver string       `json:"domain_resolver,omitempty"`
}

// OutboundTLS describes TLS settings for an outbound connection.
type OutboundTLS struct {
	Enabled    bool     `json:"enabled"`
	ServerName string   `json:"server_name,omitempty"`
	UTLS       *UTLS    `json:"utls,omitempty"`
	Reality    *Reality `json:"reality,omitempty"`
}

// UTLS describes the uTLS client fingerprint.
type UTLS struct {
	Enabled     bool   `json:"enabled"`
	Fingerprint string `json:"fingerprint,omitempty"`
}

// Reality describes the REALITY handshake parameters.
type Reality struct {
	Enabled   bool   `json:"enabled"`
	PublicKey string `json:"public_key"`
	ShortID   string `json:"short_id,omitempty"`
}

// DNS configures sing-box DNS servers and routing.
type DNS struct {
	Servers        []DNSServer `json:"servers"`
	Rules          []DNSRule   `json:"rules"`
	Final          string      `json:"final"`
	Strategy       string      `json:"strategy"`
	ReverseMapping bool        `json:"reverse_mapping"`
}

// DNSServer describes one sing-box DNS transport.
type DNSServer struct {
	Type   string `json:"type"`
	Tag    string `json:"tag"`
	Server string `json:"server,omitempty"`
	Path   string `json:"path,omitempty"`
	Detour string `json:"detour,omitempty"`
}

// DNSRule selects a DNS server for matching domains or rule-sets.
type DNSRule struct {
	DomainSuffix []string `json:"domain_suffix,omitempty"`
	RuleSet      []string `json:"rule_set,omitempty"`
	Server       string   `json:"server"`
}

// Route configures sing-box traffic routing.
type Route struct {
	Rules                 []RouteRule `json:"rules"`
	RuleSets              []RuleSet   `json:"rule_set"`
	Final                 string      `json:"final"`
	AutoDetectInterface   bool        `json:"auto_detect_interface"`
	DefaultDomainResolver string      `json:"default_domain_resolver"`
}

// RouteRule describes one ordered sing-box route rule.
type RouteRule struct {
	Action       string   `json:"action,omitempty"`
	Protocol     string   `json:"protocol,omitempty"`
	IPCIDR       []string `json:"ip_cidr,omitempty"`
	DomainSuffix []string `json:"domain_suffix,omitempty"`
	RuleSet      []string `json:"rule_set,omitempty"`
	IPIsPrivate  bool     `json:"ip_is_private,omitempty"`
	Outbound     string   `json:"outbound,omitempty"`
}

// RuleSet points sing-box at a local source or binary rule-set.
type RuleSet struct {
	Type   string `json:"type"`
	Tag    string `json:"tag"`
	Format string `json:"format"`
	Path   string `json:"path"`
}

// SourceRuleSet is the JSON source representation accepted by sing-box.
type SourceRuleSet struct {
	Version int                 `json:"version"`
	Rules   []SourceRuleSetRule `json:"rules"`
}

// SourceRuleSetRule describes one source rule-set entry.
type SourceRuleSetRule struct {
	IPCIDR       []string `json:"ip_cidr,omitempty"`
	DomainSuffix []string `json:"domain_suffix,omitempty"`
}

// Experimental contains optional sing-box integrations.
type Experimental struct {
	ClashAPI ClashAPI `json:"clash_api"`
}

// ClashAPI configures the sing-box Clash-compatible controller.
type ClashAPI struct {
	ExternalController string `json:"external_controller"`
	Secret             string `json:"secret"`
}
